import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useSelector, useDispatch } from 'react-redux'
import { Button, Container, Table } from 'react-bootstrap';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { deleteUser, getUsers } from '../redux/acions';
export default function Home() {
  const users = useSelector(state => state);
  const dispatch = useDispatch();
  const router = useRouter();
  useEffect(()=>{
    dispatch(getUsers());
  },[]);

  const edit = (e, data) => {
    e.preventDefault();
    router.push({pathname: '/updateuser',query:data});
  }

  const delet = (e, id) => {
    e.preventDefault();
    dispatch(deleteUser(id));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>

        <Button href='/adduser' variant='success' className='m-3'>Add User</Button>
        <Table striped bordered>
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Email</th>
              <th>Age</th>
              <th>Action</th>
            </tr>
          </thead>

          <tbody>
            {
              users.map(user => (
                <tr key={user.id}>
                  <td>{user.id}</td>
                  <td>{user.name}</td>
                  <td>{user.email}</td>
                  <td>{user.age}</td>
                  <td><Button variant='info' onClick={(e)=>edit(e, user)}>Edit</Button>&nbsp;
                  <Button variant='danger' onClick={(e)=>delet(e, user.id)}> Delete</Button></td>
                </tr>
              ))
            }
          </tbody>
        </Table>
      </Container>
    </div>
  )
}
